title: FIEPI
description: Notebook
url: https://jekyll.fiepi.com
keywords: ["Programming", "Blog"]
timezone: Asia/Shanghai
permalink: :title.html

about: "null"

author:
  codepen: 
  disqus: 
  dribbble: 
  email: fiepi.dev@gamil.com
  facebook: 
  flickr: 
  foursquare: 
  github: fiepi
  google_analytics: 
  google_plus: 
  instagram: 
  lastfm: 
  linkedin: 
  name: fiepi
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  telegram: fiepi
  tumblr: 
  twitter: 
  weibo: 
  xing: 
  youtube: 

color:
    user_bg: deep-orange

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - kramdown

feed:
  path: atom.xml

kramdown:
  input: GFM

paginate: 5
paginate_path: 'page/:num'

sass:
  style: compressed

color:
  default: "deep-purple"
  accent: "blue"

exclude: ['README.md', 'CHANGELOG.md', 'Gemfile.lock', 'Gemfile', 'jekyll-materialize-mod.gemspec', 'LICENSE']
