title: 玛修·基列莱特
description: 先輩最低です
url: https://blog.fiepi.com
keywords: ["Linux", "Arch Linux", "Android", "Blog"]
timezone: Asia/Shanghai
permalink: :categories/:title.html

about: "null"

author:
  codepen: 
  disqus: fiepi
  dribbble: 
  email: fiepi.dev@gamil.com
  facebook: 
  flickr: 
  foursquare: 
  github: fiepi
  google_analytics: UA-98638990-2
  google_plus: 
  instagram: 
  lastfm: 
  linkedin: 
  name: "Mash Kyrielight"
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  telegram: fiepi
  tumblr: https://nekopara.cat
  twitter: 
  weibo: 
  xing: 
  youtube: 

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml

kramdown:
  input: GFM

paginate: 5
paginate_path: 'page/:num'

sass:
  style: compressed

color:
  theme_color: "#e91e63"
  sidebar_avatar_bg_color: "pink base"
  nav_bg_color: "#e91e63"
  post_card_color: "pink darken-1"
  post_card_color_light: "pink lighten-4"

exclude: ['README.md', 'CHANGELOG.md', 'Gemfile.lock', 'Gemfile', 'jekyll-materialize-mod.gemspec', 'LICENSE']
